
CREATE TABLE public.news (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description varchar(255) NULL,
    image varchar(255) NULL,
    title varchar(255) NULL,
    username varchar(255) NULL,
    user_id uuid NULL,
 CONSTRAINT news_pkey PRIMARY KEY (id)
);

ALTER TABLE public.news ADD CONSTRAINT fki09n75txtudw1kawj5o7i8xag FOREIGN KEY (user_id) REFERENCES public.users(id);

CREATE TABLE public.tags (
    id int8 NOT NULL,
    title varchar(255) NULL,
    news_id int8 NULL,
    CONSTRAINT tags_pkey PRIMARY KEY (id)
);

ALTER TABLE public.tags ADD CONSTRAINT fk53nvualsthq4ij10ad2xfsi01 FOREIGN KEY (news_id) REFERENCES public.news(id);

CREATE TABLE public.users (
    id uuid NOT NULL,
    avatar varchar(255) NULL,
    email varchar(255) NULL,
    "name" varchar(255) NULL,
    "password" varchar(255) NULL,
    "role" varchar(255) NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE public.logs (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp NULL,
    "method" varchar(255) NULL,
    status_code int4 NULL,
    CONSTRAINT logs_pkey PRIMARY KEY (id)
);